/* Every amount is an integer number of fictional hundredths, never real money. */
(() => {
 "use strict";
 const KEY="future-money-town-v1", INITIAL=2000;
 const fresh=()=>({version:1,tab:"jars",unassigned:INITIAL,save:0,spend:0,give:0,allocated:false,interest:0,spent:0,donated:0,year:0,statements:[],bankSeen:false,bankLearned:false,riskLearned:false,strategy:null,marketSeen:false,purpose:"books",pending:null,products:[{id:"example-book",name:"一本绘本",price:600,example:true,sold:false},{id:"example-puzzle",name:"一盒拼图",price:1200,example:true,sold:false}],log:[],chatIndex:0,chatKey:""});
 let s=fresh(),feedback="",storageOK=true;
 try{const saved=JSON.parse(localStorage.getItem(KEY)||"null");if(saved?.version===1){
   const moneyKeys=["unassigned","save","spend","give","interest","spent","donated"];
   const valid=moneyKeys.every(k=>Number.isSafeInteger(saved[k])&&saved[k]>=0)
     && saved.unassigned+saved.save+saved.spend+saved.give+saved.spent+saved.donated===INITIAL+saved.interest;
   if(valid){s={...s,...saved};s.products=Array.isArray(saved.products)?saved.products.filter(p=>typeof p.id==="string"&&typeof p.name==="string"&&Number.isSafeInteger(p.price)&&p.price>0).slice(0,20):s.products;s.log=Array.isArray(saved.log)?saved.log.slice(-30):[];s.statements=Array.isArray(saved.statements)?saved.statements.slice(0,3):[];s.year=s.statements.length;}
 }}catch{storageOK=false;}
 const root=document.getElementById("lab-main"),modal=document.getElementById("lab-modal");
 const h=v=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]);
 const money=n=>(n/100).toFixed(2).replace(/\.00$/,"").replace(/(\.\d)0$/,"$1");
 const labels={save:"存",spend:"花",give:"捐"};
 const log=text=>{s.log.push(text);s.log=s.log.slice(-30);};
 const balance=()=>s.unassigned+s.save+s.spend+s.give;
 function save(){try{localStorage.setItem(KEY,JSON.stringify(s));storageOK=true;}catch{storageOK=false;}document.getElementById("lab-storage").textContent=storageOK?"自动保存到本机 · 未连接真实账户":"本次可以玩，但无法保存；请先不要关闭页面。";}
 const btn=(text,id,disabled=false,secondary=false)=>`<button type="button" class="${secondary?"secondary-action":"primary-button"}" data-lab-action="${id}" ${disabled?"disabled":""}>${h(text)}</button>`;
 const S=(text,mood="welcome")=>({who:"sunny",mood,text}),T=text=>({who:"tuan",mood:"curious",text});
 const tabs={jars:"① 存·花·捐",bank:"② 模拟银行",market:"③ 风险观察",shop:"我的实物清单",parent:"家长设置"};
 const allowed=tab=>tab==="jars"||tab==="parent"||s.allocated&&(tab!=="market"||s.bankLearned);
 if(!Object.hasOwn(tabs,s.tab)||!allowed(s.tab))s.tab="jars";
 function dialogue(){
  if(feedback)return[S(feedback,"gentle")];
  if(s.tab==="jars")return[T("这次有 20 枚零花钱，我想自己安排！"),S("可以存起来、现在花，或留给想支持的事。比例由你决定。"),S("捐的部分可以是 0。帮忙、分享时间，也有价值。","gentle")];
  if(s.tab==="bank")return[T("存进去的钱，为什么可能变多？"),S("银行按存入的钱、利率和时间，计算给你的利息。"),S("这里用虚构的年利率 5% 做实验，不是现实银行报价。"),S("快进一年只是模拟。真实的钱不会点一下就多出来。","gentle")];
  if(s.tab==="market")return[T("别人说会赚钱，我就跟着买吗？"),S("先弄懂它。钱可能变多，也可能变少；不买也是决定。"),S("我们用另外 100 实验点观察，不动你的存、花、捐。"),S("同一计划遇到不同情况，结果会怎样？一起比较。","curious")];
  if(s.tab==="shop")return[T("我想用‘花’口袋，买一件自己喜欢的东西。"),S("先看看价格和还剩多少，也可以决定等一等。"),S("这是虚拟购买申请。实物是否提供，要和家长商量。","gentle")];
  return[S("这里请家长操作。把愿意提供的实物和模拟价格写下来。"),S("本机确认没有验证家长身份，不能当作正式支付或兑换系统。","gentle")];
 }
 function jars(){return `<h2>20 枚，怎么分由我决定</h2><div class="wallet-strip"><span>还没分配</span><strong>${money(s.unassigned)} 枚</strong></div><div class="jar-allocations">${["save","spend","give"].map((k,i)=>`<article class="jar-allocation"><span aria-hidden="true">${["🏦","👛","💛"][i]}</span><div><h2>${labels[k]}</h2><p>${["放进模拟银行，留给以后","留在手边，准备买东西","留给想支持的事，可选 0"][i]}</p></div><div class="jar-counter"><button type="button" data-jar="${k}" data-delta="-1" ${s[k]===0?"disabled":""} aria-label="从${labels[k]}口袋取回最多1枚">−</button><output>${money(s[k])}</output><button type="button" data-jar="${k}" data-delta="1" ${s.unassigned===0?"disabled":""} aria-label="往${labels[k]}口袋放入最多1枚">+</button></div></article>`).join("")}</div><p class="helper-copy">每次移动 1 枚。不足 1 枚时移动剩下的部分。想改比例，先用 − 拿回，再用 + 放入另一个口袋。</p><p class="balance-equation">存 ${money(s.save)} + 花 ${money(s.spend)} + 捐 ${money(s.give)} + 未分 ${money(s.unassigned)} = ${money(balance())} 枚</p><div class="thinking-actions">${btn("这是我的分配，去银行看看 →","allocate",s.unassigned!==0)}</div><details><summary>如果我想支持一个小项目</summary><p>不会要求你捐出多少。下面的去向都是虚构教学情境，不会向组织转账。</p><div class="bank-transfer"><button type="button" class="secondary-action" data-purpose="books" aria-pressed="${s.purpose==="books"}">社区图书角</button><button type="button" class="secondary-action" data-purpose="animals" aria-pressed="${s.purpose==="animals"}">小动物照护</button></div><p>现在选择：${s.purpose==="animals"?"小动物照护":"社区图书角"}</p>${btn("模拟捐出 1 枚，先确认","donate",s.give<100,true)}</details>`;}
 function bank(){const last=s.statements.at(-1);return `<h2>钱、时间和利息</h2><div class="wallet-strip"><span>我存在模拟银行的钱</span><strong>${money(s.save)} 枚</strong></div><p class="goal-note">教学假设：年利率 5%，每满一个模拟年结一次利息。没有手续费与税；现实规则可能不同。</p><div class="bank-statement"><h3>先看一个例子，不改变你的余额</h3><dl><dt>原来存入（本金）</dt><dd>20 枚</dd><dt>存 1 年的利息</dt><dd>20 × 5% = 1 枚</dd><dt>一年后</dt><dd>20 + 1 = 21 枚</dd></dl></div><div class="thinking-actions">${btn("看懂这个例子，试着回答","bank-example",s.bankSeen,true)}${btn(s.year<3?`让我的存款经过第 ${s.year+1} 年 →`:"已观察 3 年","bank-year",s.year>=3||s.save===0)}</div>${s.save===0?'<p class="helper-copy">你可以选择暂时不存钱，仍然能看例子学习。想存时，再回去调整分配。</p>':""}${last?`<div class="bank-statement" role="status"><h3>第 ${s.year} 年的真实模拟记录</h3><dl><dt>这一年开始有</dt><dd>${money(last.start)} 枚</dd><dt>这一年得到利息</dt><dd>+ ${money(last.gain)} 枚</dd><dt>结息时银行余额</dt><dd>${money(last.end)} 枚</dd></dl><p class="helper-copy">已计入余额。再刷新不会多发一次。小数表示不足 1 枚的部分。</p></div>`:""}<div class="bank-transfer">${btn("取出最多 1 枚到‘花’","withdraw",s.save===0,true)}${btn("从‘花’存入最多 1 枚","deposit",s.spend===0,true)}</div><p class="helper-copy">转存、取出只是换口袋，不是利息。利息留在银行，下一年会一起参与计算；最多观察 3 年，不用连续刷奖励。</p>${s.bankSeen?`<section class="lab-quiz"><h3>例子里多出的 1 枚，是什么？</h3><button type="button" data-bank-answer="deposit">我又存进去的本金</button><button type="button" data-bank-answer="interest">银行按利率和时间给的利息</button><button type="button" data-bank-answer="market">股票一定会赚的钱</button>${s.bankLearned?'<p class="goal-note">✓ 已区分本金与利息。可以去做风险观察，也可以先休息。</p>':""}</section>`:""}`;}
 function market(){const results=s.strategy==="wait"?[100,100,100]:s.strategy==="one"?[102,96,98]:[99,96,100];return `<h2>同一决定，看看三种可能</h2><p class="goal-note">独立实验点：100。不是存款，也不是未来预测。下面三个情境只是例子，不代表发生概率。</p><div class="market-strategies"><button type="button" data-strategy="wait" aria-pressed="${s.strategy==="wait"}">先不买，保留 100 实验点</button><button type="button" data-strategy="one" aria-pressed="${s.strategy==="one"}">80 点不动，20 点放在饮品公司</button><button type="button" data-strategy="split" aria-pressed="${s.strategy==="split"}">80 点不动，饮品和游戏公司各 10 点</button></div><div class="thinking-actions">${btn("比较三种情况，不猜涨跌 →","market-run",!s.strategy)}</div>${s.marketSeen?`<div class="market-outcomes">${[["情境一：有涨有跌","饮品 +10%，游戏 −20%"],["情境二：一起下跌","两家公司都 −20%"],["情境三：方向相反","饮品 −10%，游戏 +10%"]].map(([title,copy],i)=>`<article><h3>${title}</h3><p>${copy}</p><strong>${results[i]} 点</strong><span class="change">${results[i]>100?"+":""}${results[i]-100} 点</span></article>`).join("")}</div><p class="helper-copy">这里保留的实验点不计利息、费用和通胀。不买避免了本例的市场涨跌，但现实仍有其他需要考虑的因素。</p><section class="lab-quiz"><h3>分到两家公司，就能保证不亏吗？</h3><button type="button" data-risk-answer="yes">能，分散就一定安全</button><button type="button" data-risk-answer="no">不能，好几家公司也可能一起跌</button>${s.riskLearned?'<p class="goal-note">✓ 你发现了：分散不能消除风险。需要时先保留现金，不懂的先了解，也可以不投资。</p>':""}</section>`:""}<p class="lab-warning">两家公司只是入门示意，不代表充分分散。不提供真实证券、交易入口、收益排名或投资建议。</p>`;}
 function shop(){return `<h2>我想买，也可以等一等</h2><div class="wallet-strip"><span>‘花’口袋可以用</span><strong>${money(s.spend)} 枚</strong></div>${s.pending?`<div class="goal-note">已提交：${h(s.pending.name)} · ${money(s.pending.price)} 枚。<br />还没扣币，等家长一起看。${btn("取消这个申请","cancel-order",false,true)}</div>`:""}<div class="lab-shop">${s.products.map(p=>`<article class="lab-product"><h3>${p.example?"📋":"🎁"} ${h(p.name)}</h3><small>${p.example?"教学示例，尚未由家长提供实物":"家长录入的实物 · 是否交付仍需当面确认"}</small><span class="lab-price">${money(p.price)} 枚模拟币</span><small>${s.spend>=p.price?`如果买下，‘花’口袋还剩 ${money(s.spend-p.price)} 枚。`:`还差 ${money(p.price-s.spend)} 枚。可以等、换一样，或回去重新分配。`}</small>${btn(p.sold?"本次已模拟买过":"我想买，先比较一下",`buy:${p.id}`,p.sold||Boolean(s.pending))}</article>`).join("")}</div><p class="lab-warning">没有真实付款。示例不是可售库存；家长录入的项目也不会自动交付。不要填写真实账号、地址或联系方式。</p>`;}
 function parent(){return `<h2>把生活里的物品放进练习</h2><p class="parent-note">这是同一台设备上的家长演示区，没有身份验证。不能防止孩子自行点击确认，也不能用于真实收费、自动兑换或正式家长授权。</p><form class="parent-form" id="product-form"><label>愿意提供的实物名称<input id="product-name" type="text" required maxlength="30" placeholder="例如：家里备用的一套贴纸" autocomplete="off" /></label><label>模拟价格（1–100 枚）<input id="product-price" type="number" min="1" max="100" step="1" value="5" required /></label><label><span><input id="product-consent" type="checkbox" required /> 我有权提供这件物品，了解这里只记录模拟申请</span></label><button class="primary-button" type="submit" ${s.products.filter(p=>!p.example).length>=12?"disabled":""}>加入孩子的实物清单</button></form><p class="helper-copy">最多 12 件家长项目，每件按一次模拟购买处理。建议选额外的小物件，不把基本生活需要设成必须赚币才能得到的奖励。</p>${s.pending?`<section class="bank-statement"><h3>待一起确认</h3><p>${h(s.pending.name)} · ${money(s.pending.price)} 枚模拟币</p><p class="helper-copy">确认只扣除虚拟‘花’口袋余额并标记本次模拟完成，不代表实物已交付。</p><div class="thinking-actions">${btn("家长确认这次模拟选择","approve")}${btn("先不买，取消申请","cancel-order",false,true)}</div></section>`:""}<details><summary>本机小账本</summary>${history()}</details><details><summary>家长说明与教学依据</summary><p>先自己分配，再学习利息，最后才开放市场观察。不设置固定‘正确比例’，0 捐赠和不投资都允许。当前不接真实银行、支付、慈善组织或证券账户。</p><p>存款按虚构固定年利率 5% 演示，一年一次结息，四舍五入至 0.01 枚，利息计入本金。真实利率、计息方法、风险和条款须另行核实。</p><p>资料参考：<a href="https://moneysmart.gov.au/family-and-relationships/teaching-kids-about-money" target="_blank" rel="noopener noreferrer">Moneysmart 儿童金钱教育</a>、<a href="https://moneysmart.gov.au/how-to-invest/diversification" target="_blank" rel="noopener noreferrer">分散与风险</a>。这些资料不是对本产品的认证。</p><p>只保存本机模拟记录，不上传儿童资料。设备语音可能联网。没有真实儿童试用数据，不将完成任务当作已掌握金融能力。</p></details><div class="thinking-actions">${btn("重置这一轮小镇演示","reset",false,true)}</div>`;}
 function history(){return `<p class="balance-equation">初始 20 + 利息 ${money(s.interest)} − 模拟消费 ${money(s.spent)} − 模拟捐出 ${money(s.donated)} = 当前 ${money(balance())} 枚</p><ol class="lab-log">${s.log.map(v=>`<li>${h(v)}</li>`).join("")||"<li>还没有交易。分配是在口袋之间移动，不是收入。</li>"}</ol>`;}
 function render(focus=false){window.TeachingMedia.dispose();root.innerHTML=`<p class="course-kicker">先在游戏里试一试，再和家长带回生活</p><div class="thinking-title"><h1 id="lab-heading" tabindex="-1">我的钱，我来安排</h1><span>虚拟练习</span></div><nav class="lab-nav" aria-label="小镇地点">${Object.entries(tabs).map(([id,label])=>`<button type="button" data-tab="${id}" ${s.tab===id?'aria-current="page"':""} ${allowed(id)?"":"disabled"}>${h(label)}${allowed(id)?"":" 🔒"}</button>`).join("")}</nav><div class="lab-summary"><span>🏦 存 <strong>${money(s.save)}</strong></span><span>👛 花 <strong>${money(s.spend)}</strong></span><span>💛 捐 <strong>${money(s.give)}</strong></span></div><div class="thinking-layout"><aside class="thinking-chat"><div class="dialogue-slot"></div></aside><section class="thinking-work">${{jars,bank,market,shop,parent}[s.tab]()}<p class="lab-feedback" role="status">${h(feedback)}</p></section></div>`;
  const key=`${s.tab}:${feedback||"intro"}`;if(key!==s.chatKey){s.chatKey=key;s.chatIndex=0;}
  window.TeachingMedia.mount(root,{english:false,stage:0,text:"",dialogue:dialogue(),dialogueIndex:s.chatIndex,onDialogueChange(i){s.chatIndex=i;save();}});
  root.querySelectorAll("[data-tab]").forEach(b=>b.addEventListener("click",()=>{if(allowed(b.dataset.tab)){s.tab=b.dataset.tab;feedback="";render(true);}}));
  root.querySelectorAll("[data-jar]").forEach(b=>b.addEventListener("click",()=>{const k=b.dataset.jar,add=b.dataset.delta==="1",n=Math.min(100,add?s.unassigned:s[k]);if(!n)return;if(add){s.unassigned-=n;s[k]+=n;}else{s[k]-=n;s.unassigned+=n;}feedback="";render();root.querySelector(`[data-jar="${k}"][data-delta="${b.dataset.delta}"]`)?.focus({preventScroll:true});}));
  root.querySelectorAll("[data-lab-action]").forEach(b=>b.addEventListener("click",()=>act(b.dataset.labAction)));
  root.querySelectorAll("[data-purpose]").forEach(b=>b.addEventListener("click",()=>{s.purpose=b.dataset.purpose;feedback="";render();}));
  root.querySelectorAll("[data-bank-answer]").forEach(b=>b.addEventListener("click",()=>{if(!s.bankSeen)return;const ok=b.dataset.bankAnswer==="interest",first=!s.bankLearned;if(ok)s.bankLearned=true;say(ok?"对，额外的 1 枚是利息；原来的 20 枚是本金。利息需要时间，不是魔法。":"一起分开看：自己存入的叫本金，银行按约定给的部分叫利息。",ok&&first);}));
  root.querySelectorAll("[data-strategy]").forEach(b=>b.addEventListener("click",()=>{s.strategy=b.dataset.strategy;s.marketSeen=false;feedback="";render();}));
  root.querySelectorAll("[data-risk-answer]").forEach(b=>b.addEventListener("click",()=>{if(!s.marketSeen)return;const ok=b.dataset.riskAnswer==="no",first=!s.riskLearned;if(ok)s.riskLearned=true;say(ok?"你注意到了共同下跌的情况。分散能减少单一公司的影响，但不能保证不亏。":"看看第二种情况：两家公司一起跌了。分散不能把风险变成零。",ok&&first);}));
  root.querySelector("#product-form")?.addEventListener("submit",e=>{e.preventDefault();const name=root.querySelector("#product-name").value.trim(),n=Number(root.querySelector("#product-price").value);if(!name||name.length>30||!Number.isInteger(n)||n<1||n>100||!root.querySelector("#product-consent").checked||s.products.filter(p=>!p.example).length>=12)return;s.products.push({id:`family-${Date.now()}-${s.products.length}`,name,price:n*100,example:false,sold:false});say("已加入清单。孩子可以自己比较，也可以决定先不买。");});
  save();if(focus){window.scrollTo({top:0,behavior:"instant"});document.getElementById("lab-heading").focus({preventScroll:true});}
 }
 function say(text,chime=false){feedback=text;render();if(chime)window.TeachingMedia.playSuccessSound();}
 function confirm(title,copy,run){window.TeachingMedia.suspend();modal.innerHTML=`<h2 id="lab-modal-title">${h(title)}</h2><p>${h(copy)}</p><div class="dialog-actions"><button type="button" data-dismiss>再想想</button><button type="button" data-confirm>确认这次模拟</button></div>`;modal.querySelector("[data-dismiss]").onclick=()=>modal.close();modal.querySelector("[data-confirm]").onclick=()=>{modal.close();run();};modal.showModal();}
 function act(id){
  if(id==="allocate"&&s.unassigned===0){s.allocated=true;s.tab="bank";feedback="";render(true);return;}
  if(id==="bank-example"&&s.allocated){s.bankSeen=true;say("20 枚存满一个模拟年，利息是 1 枚。这个例子没有动你的钱。下面说说你的发现。");return;}
  if(id==="bank-year"&&s.allocated&&s.save>0&&s.year<3){const start=s.save,gain=Math.round(start*5/100);s.save+=gain;s.interest+=gain;s.year++;s.bankSeen=true;s.statements.push({start,gain,end:s.save});log(`第 ${s.year} 年：本金 ${money(start)}，利息 +${money(gain)}，银行变为 ${money(s.save)}。`);say(`一年过去，利息是 ${money(gain)} 枚。余额变化已记在账本里。`);return;}
  if(id==="withdraw"||id==="deposit"){if(!s.allocated)return;const from=id==="withdraw"?"save":"spend",to=id==="withdraw"?"spend":"save",n=Math.min(100,s[from]);if(n===0)return;s[from]-=n;s[to]+=n;log(`从‘${labels[from]}’转 ${money(n)} 枚到‘${labels[to]}’，总额没变。`);say("这是移动自己的钱，总额没有增加；它不是利息。");return;}
  if(id==="donate"&&s.give>=100){confirm("模拟捐出 1 枚？",`从‘捐’口袋拿出 1 枚，支持虚构的${s.purpose==="animals"?"小动物照护":"社区图书角"}。没有真实转账，你也可以取消。`,()=>{if(s.give<100)return;s.give-=100;s.donated+=100;log(`模拟捐出 1 枚：${s.purpose==="animals"?"小动物照护":"社区图书角"}。`);say("模拟捐出已记下。决定捐多少由你自己来，不按金额给分。");});return;}
  if(id==="market-run"&&s.bankLearned&&["wait","one","split"].includes(s.strategy)){s.marketSeen=true;say("这三个结果来自预设情境，不是在预测未来。注意：同一选择也会遇到不同结果。");return;}
  if(id.startsWith("buy:")&&s.allocated&&!s.pending){const p=s.products.find(v=>v.id===id.slice(4));if(!p||p.sold)return;if(s.spend<p.price){say(`‘花’口袋还差 ${money(p.price-s.spend)} 枚。可以等一等，或回去重新分配；不会自动动用你的存款。`);return;}confirm(`想买${p.name}？`,`需要 ${money(p.price)} 枚，确认后会提交模拟申请。现在不扣币，家长也可以一起决定暂时不买。`,()=>{if(s.pending||p.sold)return;s.pending={id:p.id,name:p.name,price:p.price};log(`申请模拟购买：${p.name}，${money(p.price)} 枚；未扣币。`);say("申请留下了。还没付款，也没有自动交付实物。可以请家长一起看。");});return;}
  if(id==="cancel-order"&&s.pending){log(`取消申请：${s.pending.name}；没有扣币。`);s.pending=null;say("申请取消了，钱还在你的口袋里。");return;}
  if(id==="approve"&&s.pending){const order=s.pending,p=s.products.find(v=>v.id===order.id);if(!p||p.sold){s.pending=null;say("这件物品已不可用，申请已取消，没有扣币。");return;}if(s.spend<order.price){say("‘花’口袋余额已变化，现在不够。没有扣币；请和孩子重新讨论。");return;}confirm("只确认虚拟购买记录",`${order.name}：扣 ${money(order.price)} 枚模拟币。此操作不是真实支付、家长身份验证或实物交付。`,()=>{if(!s.pending||s.pending.id!==order.id||p.sold||s.spend<order.price)return;s.spend-=order.price;s.spent+=order.price;p.sold=true;s.pending=null;log(`模拟购买完成：${order.name}，−${money(order.price)} 枚；不代表已交付。`);say("这次模拟购买已记账。实物如何提供，仍由家长和孩子在线下确认。");});return;}
  if(id==="reset"){confirm("重置这一轮小镇？","这会清除本机小镇的余额、实物清单和申请，重新得到 20 枚练习币。野餐思考课和原六课进度都保留。",()=>{s=fresh();feedback="";render(true);});}
 }
 document.getElementById("lab-pause").addEventListener("click",()=>{window.TeachingMedia.suspend();save();modal.innerHTML='<span class="sunny-sprite" data-mood="gentle" aria-hidden="true"></span><h2 id="lab-modal-title">休息一下，决定不用着急。</h2><p>进度留在这台设备。准备好了再继续。</p><button class="primary-button" type="button" data-resume>我准备好了</button>';modal.querySelector("[data-resume]").onclick=()=>modal.close();modal.showModal();});
 window.addEventListener("pagehide",save);render();
})();
